feat(just): added btrfs scrub commands

diff --git a/dot_config/just/justfile b/dot_config/just/justfile
--- a/dot_config/just/justfile
+++ b/dot_config/just/justfile
@@ -1,12 +1,14 @@
 # -- VARIABLES -----------------------------------------------------------
 
-doom := env("HOME") + "/.config/emacs/bin/doom"
-dk_enc := env("HOME") + "/0-doctorkotik/0-core/3-RESOURCES/program-data/dk.enc"
+dk_core := env("HOME") + "/0-doctorkotik/0-core"
+
+dk_enc := dk_core + "/3-RESOURCES/program-data/dk.enc"
 dk_mnt := env("HOME") + "/mount/dk.dec"
-btrbk_dir := env("HOME") + "/0-doctorkotik/0-core/3-RESOURCES/program-data/btrbk"
+btrbk_dir := dk_core + "/3-RESOURCES/program-data/btrbk"
 btrbk_bin := btrbk_dir + "/bin/btrbk"
-kagi_enc := env("HOME") + "/0-doctorkotik/0-core/3-RESOURCES/program-data/old-places/kagi.age"
+kagi_enc := dk_core + "/3-RESOURCES/program-data/old-places/kagi.age"
 kagi_tmp := "/dev/shm/kagi"
+doom := env("HOME") + "/.config/emacs/bin/doom"
 
 # -- SETUP (one-off, per machine) -----------------------------------------
 
@@ -52,6 +54,20 @@ gocryptfs-mount:
 gocryptfs-unmount:
     fusermount -u {{dk_mnt}}
 
+
+# -- MAINTENANCE ----------------------------------------------------------
+
+laptop-btrfs-scrub:
+    #!/usr/bin/env bash
+    set -euo pipefail
+    if gum confirm "Scrub laptop filesystem?"; then
+        sudo btrfs scrub start -B {{dk_core}}
+        echo ""
+        sudo btrfs scrub status {{dk_core}}
+    else
+        echo "Aborted."
+    fi
+
 btrbk-backup:
     #!/usr/bin/env bash
     set -euo pipefail
@@ -62,11 +78,15 @@ btrbk-backup:
     if gum confirm "Run btrbk -c ${config}.conf ${action}?"; then
         sudo {{btrbk_bin}} -c {{btrbk_dir}}/${config}.conf "$action"
         sync
+        target=$(grep -E '^\s*target\s+' {{btrbk_dir}}/${config}.conf | awk '{print $2}' | head -1)
+        if gum confirm --default=false "Also scrub target ($target) while it's mounted?"; then
+            sudo btrfs scrub start -B "$target"
+            echo ""
+            sudo btrfs scrub status "$target"
+        fi
     else
         echo "Aborted."
     fi
-
-# -- MAINTENANCE ----------------------------------------------------------
 
 git-import-jj-config:
     #!/usr/bin/env bash
